# Generated by Django 4.2.19 on 2025-03-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgingCriteria',
            fields=[
                ('criteriaId', models.AutoField(primary_key=True, serialize=False)),
                ('criterionName', models.CharField(max_length=255)),
                ('maxPoints', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phaseId', models.AutoField(primary_key=True, serialize=False)),
                ('phaseName', models.CharField(max_length=255)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=255)),
                ('accumulatedPoint', models.IntegerField()),
                ('affiliation', models.CharField(max_length=255)),
                ('lateSubmissionDateTime', models.DateTimeField()),
                ('currentPhase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submissionId', models.AutoField(primary_key=True, serialize=False)),
                ('SubmissionDateTime', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.phase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('scoreId', models.AutoField(primary_key=True, serialize=False)),
                ('criteriaId', models.IntegerField()),
                ('assignedPoints', models.IntegerField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('participantId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('cohort', models.CharField(blank=True, max_length=255, null=True)),
                ('dateJoined', models.DateTimeField()),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('confidenceScore', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.team')),
            ],
        ),
    ]
