# Generated by Django 5.2 on 2025-04-09 10:39

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgingCriteria',
            fields=[
                ('criteriaId', models.AutoField(primary_key=True, serialize=False)),
                ('criterionName', models.CharField(max_length=255)),
                ('maxPoints', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phaseId', models.AutoField(primary_key=True, serialize=False)),
                ('phaseName', models.CharField(max_length=255)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=255)),
                ('league', models.CharField(max_length=255)),
                ('accumulatedPoint', models.IntegerField()),
                ('affiliation', models.CharField(max_length=255)),
                ('lateSubmissionDateTime', models.DateTimeField()),
                ('currentPhase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submissionId', models.AutoField(primary_key=True, serialize=False)),
                ('SubmissionDateTime', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.phase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('scoreId', models.AutoField(primary_key=True, serialize=False)),
                ('criteriaId', models.IntegerField()),
                ('assignedPoints', models.IntegerField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('participantId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('cohort', models.CharField(blank=True, max_length=255, null=True)),
                ('dateJoined', models.DateTimeField()),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('confidenceScore', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.team')),
            ],
        ),
    ]
