# Generated by Django 4.2.19 on 2025-03-25 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
